// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class MergeSettings {
    /**
     * Creates a new MergeSettings instance.
     * @param {Partial<MergeSettings>} [$$source = {}] - The source object to create the MergeSettings.
     */
    constructor($$source = {}) {
        if (!("ignoreMinorErrors" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ignoreMinorErrors"] = false;
        }
        if (!("editedSuffix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["editedSuffix"] = "";
        }
        if (!("timezoneOffset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timezoneOffset"] = "";
        }
        if (!("inferTimezoneFromGPS" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["inferTimezoneFromGPS"] = false;
        }
        if (!("mergeTitle" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mergeTitle"] = false;
        }
        if (!("mergeDescription" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mergeDescription"] = false;
        }
        if (!("mergeDateTaken" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mergeDateTaken"] = false;
        }
        if (!("mergeURL" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mergeURL"] = false;
        }
        if (!("mergeGPS" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["mergeGPS"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeSettings(/** @type {Partial<MergeSettings>} */($$parsedSource));
    }
}
