// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../github.com/xob0t/go-out-backend/models.js";

/**
 * @returns {Promise<backend$0.MergeSettings> & { cancel(): void }}
 */
export function Get() {
    let $resultPromise = /** @type {any} */($Call.ByID(710695688));
    let $typingPromise = /** @type {any} */($resultPromise.then(($result) => {
        return $$createType0($result);
    }));
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * @param {backend$0.MergeSettings} settigns
 * @returns {Promise<void> & { cancel(): void }}
 */
export function Update(settigns) {
    let $resultPromise = /** @type {any} */($Call.ByID(1979435517, settigns));
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = backend$0.MergeSettings.createFrom;
